//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTBAG.Master_Data.ProductDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MASTER_SPECIFICATIONS
    {
        public int ID { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public string MEASUREMENT_NAME { get; set; }
        public string STAGE_TEXT { get; set; }
        public Nullable<double> MAX_VALUE { get; set; }
        public Nullable<double> PREFERRED_VALUE { get; set; }
        public Nullable<double> MIN_VALUE { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
