//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTBAG.Master_Data.ProductDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAW_MEASUREMENT
    {
        public int ID { get; set; }
        public Nullable<int> MEASUREMENT_ID { get; set; }
        public Nullable<double> TOTAL_SECONDS { get; set; }
        public string MEASUREMENT_NAME { get; set; }
        public Nullable<double> MEASUREMENT_VALUE { get; set; }
    }
}
