//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTBAG.Master_Data.ProductDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaiyouSenpuBagEntities2 : DbContext
    {
        public TaiyouSenpuBagEntities2()
            : base("name=TaiyouSenpuBagEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MASTER_SPECIFICATIONS> MASTER_SPECIFICATIONS { get; set; }
        public virtual DbSet<MEASUREMENT_PRODUCT> MEASUREMENT_PRODUCT { get; set; }
        public virtual DbSet<PRODUCT> PRODUCT { get; set; }
        public virtual DbSet<RAW_MEASUREMENT> RAW_MEASUREMENT { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
