//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTBAG.Master_Data.ProductDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.MASTER_SPECIFICATIONS = new HashSet<MASTER_SPECIFICATIONS>();
        }
    
        public int ID { get; set; }
        public string PRODUCT_GRUOP { get; set; }
        public string SERIES { get; set; }
        public string MODEL { get; set; }
        public string BATTERY_TYPE { get; set; }
        public string BATTERY_CAPACITY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE_TIME { get; set; }
        public Nullable<bool> IS_DEACTICATED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MASTER_SPECIFICATIONS> MASTER_SPECIFICATIONS { get; set; }
    }
}
