//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TESTBAG.Data_Management.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEASUREMENT_PRODUCT
    {
        public int ID { get; set; }
        public Nullable<int> PRODUCT_ID { get; set; }
        public string SERIAL_NUMBER { get; set; }
        public string LOT_NUMBER { get; set; }
        public Nullable<System.DateTime> MFG_DATE { get; set; }
        public Nullable<System.DateTime> MEASURE_DATE_TIME { get; set; }
        public string NG_LIST { get; set; }
        public string CREATE_BY { get; set; }
        public string JOB_NUMBER { get; set; }
        public string COMMENT { get; set; }
    }
}
